name: Update Surge Module

on:
  schedule:
    # Runs daily at 1 PM Eastern Time (18:00 UTC)
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Domain List
        run: |
          curl -L -o pro.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt

      - name: Convert to Surge Module
        run: |
          # Ensure the Surge/Modules folder exists
          mkdir -p Surge/Modules
          output_file="Surge/Modules/Ad-Telemetry-Blocking.conf"
          
          # Create a header with the update timestamp
          {
            echo "# Surge Ad and Telemetry Blocking Module"
            echo "# Updated on $(date)"
            echo ""
            echo "[Rule]"
          } > "$output_file"
          
          # Convert each valid domain line into a Surge rule
          grep -v '^#' pro.txt | grep -v '^\s*$' | while IFS= read -r domain; do
            domain=$(echo "$domain" | xargs)
            if [ -n "$domain" ]; then
              echo "DOMAIN-SUFFIX,$domain,REJECT" >> "$output_file"
            fi
          done

      - name: Commit and Push changes
        env:
          # Use the PAT stored in the ADBLOCK secret
          ADBLOCK: ${{ secrets.ADBLOCK }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Update the remote URL with the PAT for authentication
          git remote set-url origin https://$ADBLOCK@github.com/SubTek/Script.git
          
          git add Surge/Modules/Ad-Telemetry-Blocking.conf
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update Surge Ad and Telemetry Blocking Module"
            git push origin HEAD
          else
            echo "No changes detected."
          fi
